title: fengkh🔥
subtitle: null
description: 道阻且长，行则将至 🍭🍭🍭
keywords: Python,Deep Learning,Computer Vision,Object Detection,Blog,fengkh🔥
author: fengkh🔥
language: zh-CN
timezone: ''
abbrlink:
  alg: crc32
  rep: hex
url: https://fengkh.github.io
permalink: posts/:abbrlink.html
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':year-:month-:day-:title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
math:
  engine: mathjax
  mathjax:
    src: custom_mathjax_source
    config: null
aplayer:
  meting: true
  asset_inject: false
index_generator:
  path: ''
  per_page: 9
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: butterfly
deploy:
  - type: git
    repo: git@github.com:fengkh/fengkh.github.io.git # 这个Github仓库用自动部署即可
    branch: master
algolia:
  appId: ''
  apiKey: ''
  adminApiKey: ''
  chunkSize: null
  indexName: ''
  fields:
    - content:strip:truncate,0,30000
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title
swiper:
  enable: false # 开关
  priority: 1 #过滤器优先权
  enable_page: / # 应用页面
  timemode: date #date/updated
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper css依赖
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js #swiper js依赖
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css # 适配主题样式补丁
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiper初始化方法
search:
  path: search.xml
  field: post
  content: true
plugin:
  - hexo-generator-feed
feed: null
type: atom
path: atom.xml
limit: 20
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml
baidu_url_submit:
  count: 10
  host: null
  token: null
  path: null
nofollow:
  enable: false
  field: site
  exclude: ''

# hexo-filter-gitcalendar
gitcalendar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: /personal/about/ # 应用页面
  # butterfly挂载容器
  layout: # 挂载容器类型
    type: id
    # name: recent-posts
    name: gitZone
    index: 0
  user: fengkh #git用户名
  apiurl: 'https://gitcalendar.fomal.cc'	# 这是我的API，最好自己弄一个
  minheight:
    pc: 280px #桌面端最小高度
    mibile: 0px #移动端最小高度
  color: "['#d9e0df', '#c6e0dc', '#a8dcd4', '#9adcd2', '#89ded1', '#77e0d0', '#5fdecb', '#47dcc6', '#39dcc3', '#1fdabe', '#00dab9']" # 目前我在用的
  # "['#e4dfd7', '#f9f4dc', '#f7e8aa', '#f7e8aa', '#f8df72', '#fcd217', '#fcc515', '#f28e16', '#fb8b05', '#d85916', '#f43e06']" #橘黄色调
  # color: "['#ebedf0', '#fdcdec', '#fc9bd9', '#fa6ac5', '#f838b2', '#f5089f', '#c4067e', '#92055e', '#540336', '#48022f', '#30021f']" #浅紫色调
  # color: "['#ebedf0', '#f0fff4', '#dcffe4', '#bef5cb', '#85e89d', '#34d058', '#28a745', '#22863a', '#176f2c', '#165c26', '#144620']" #翠绿色调
  # color: "['#ebedf0', '#f1f8ff', '#dbedff', '#c8e1ff', '#79b8ff', '#2188ff', '#0366d6', '#005cc5', '#044289', '#032f62', '#05264c']" #天青色调
  container: .recent-post-item(style='width:100%;height:auto;padding:10px;') #父元素容器，需要使用pug语法
  gitcalendar_css: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.css
  gitcalendar_js: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.js

plugins:
  - hexo-algoliasearch

magnet:
  enable: false
  priority: 2
  enable_page: /
  type: categories
  devide: 3
  display:
    - name: Coding
      display_name: 持续头秃中...
      icon: 🍡
    - name: Environments
      display_name: 踩坑记录QAQ
      icon: 🍼
    - name: Life
      display_name: 记录美好生活啦~
      icon: 🍉
    - name: Papers
      display_name: 读论文捏>.<
      icon: 🍟
  color_setting:
    text_color: black # 文字默认颜色
    text_hover_color: white # 文字鼠标悬浮颜色
    background_color: "#e9e9e9" # 文字背景默认颜色
    background_hover_color: var(--text-bg-hover) # 文字背景悬浮颜色
  layout:
    type: id
    name: recent-posts
    index: 0
  temple_html: '<div class="recent-post-item" style="width:100%;height: auto"><div id="catalog_magnet">${temple_html_item}</div></div>'
  plus_style: ""
# categoryBar:
#   enable: false # 开关
#   priority: 5 #过滤器优先权
#   enable_page: / # 应用页面
#   layout: # 挂载容器类型
#     type: id
#     name: recent-posts
#     index: 0
#   column: odd # odd：3列 | even：4列
#   row: 1 #显示行数，默认两行，超过行数切换为滚动显示
#   message:
#     - descr: Coding
#       cover: /assets/cover.jpg
#
#     - descr: Python
#       cover: /assets/cover.jpg
#
#     - descr: Reading papers
#       cover: /assets/cover.jpg
#
#     - descr: Git
#       cover: /assets/cover.jpg
#
#     - descr: Life
#       cover: /assets/cover.jpg
#   custom_css: https://npm.elemecdn.com/hexo-butterfly-categories-card@1.0.0/lib/categorybar.css
